ParseAs for dpkg-status
google/osv-scanner pull request #229
Opened 2023-02-20 22:46 UTC by cmaritan

As previously done with apk `installed` lockfiles, I propose to add the parseAs option also for dpkg `status` files since they also have a very generic filename:

```bash
osv-scanner --lockfile 'dpkg-status:/var/lib/dpkg/status'
```

2023-02-20 23:58 UTC, another-rex approved these changes

2023-02-21 00:42 UTC, G-Rath requested changes
You should add a CLI test like the one for `apk-installed`, to confirm it works

2023-02-21 06:51 UTC, cmaritan commented
> You should add a CLI test like the one for `apk-installed`, to confirm it works

Done!

2023-02-21 07:10 UTC, G-Rath approved these changes

2023-02-22 00:29 UTC, merged