add unit tests for results.go
google/osv-scanner pull request #368
Opened 2023-05-05 14:45 UTC by khareyash05

Fixes #356

2023-05-08 00:21 UTC, another-rex requested changes
Thank you! Just a comment about changing how the final comparison is done.

2023-05-08 00:21 UTC, another-rex commented on pkg/models/results_test.go
> +	if len(flattened) != 1 {
Instead of comparing each individual field in it's own if statement, can you swap this to use `cmp.Diff(flattened, expectedFlattened)`, and create a new variable with the expected flattened structure. 

Similar to how "pkg/grouper/grouper_test.go" is done.

2023-05-09 06:26 UTC, khareyash05 commented on pkg/models/results_test.go
> +	if len(flattened) != 1 {
Will do that!

2023-05-10 01:01 UTC, another-rex approved these changes
Thanks, LGTM!

2023-05-10 01:07 UTC, another-rex commented on pkg/models/results_test.go
> +func TestFlatten(t *testing.T) {
```suggestion
func TestFlatten(t *testing.T) {
	t.Parallel()
```

2023-05-10 01:17 UTC, khareyash05 commented
@another-rex is my PR ready to merge?

2023-05-10 02:19 UTC, merged

2023-05-10 05:49 UTC, khareyash05 commented
Thank you @another-rex I would like to contribute more to this repo.Is there any communication channel like Slack for the same? So that we can discuss about the repo and that I can get a clear understanding of the code.