SARIF with fixed version
google/osv-scanner pull request #559
Opened 2023-09-28 01:04 UTC by another-rex

Add fixed version in help text. 

Also add `osv-reporter` to scheduled scanning, this allows scheduled scanning to also print out the vulnerability table as well as the SARIF.

2023-09-29 01:27 UTC, oliverchang commented on internal/output/fixtures/sarif-output.md
> +
Can you add some text around "remediation instructions" around here? 

This should say something along the lines of, update the offending package past the listed fix versions, or add this to the OSV config (link to documentation) to silence this.

2023-09-29 02:08 UTC, another-rex commented on internal/output/fixtures/sarif-output.md
> +
Done, @hayleycd can you take a look at the `sarif-output.md` file and see if there's anything you think would be better reworded? Thanks!

2023-09-29 16:56 UTC, hayleycd commented on internal/output/fixtures/sarif-output.md
> +
Hey @another-rex, can you give me some context on what this file is? Is this a sample of what a sarif output would look like? 

Does it change depending on what vulnerabilities are in my specific project? 

I am trying to understand the conditions under which a user would see this file. It doesn't look like we link to it in the docs at all?

2023-10-02 23:37 UTC, another-rex commented on internal/output/fixtures/sarif-output.md
> +
So this file is what you will see when looking at the output in `Security > Code Scanning` tab, e.g. 
![image](https://github.com/google/osv-scanner/assets/106129829/0d54eaee-bc01-4d50-ab28-7eea8fd4e9a7)

This doc is an example of what will be displayed between "Your dependency is vulnerable to..." and "Show less ^". In this case the `sarif-output.md` is just a specific output we are using to test the behavior of the code generating the SARIF file, the actual "template" is located at the top of the `sarif.go` file (https://github.com/google/osv-scanner/pull/559/files#diff-d35339a2a0d00fb1bdef55bde8021cf88c25c1817a1d1f8afcfd734a1e80a784L29)

2023-10-02 23:41 UTC, oliverchang reviewed
nice! Just one more minor suggestion to nail the UX.

2023-10-02 23:41 UTC, oliverchang commented on internal/output/fixtures/sarif-output.md
> +`path/to/lockfile-parent-dir/osv-scanner.toml`
Can we auto-populate these? 

We know where the lockfile lives, and we also know which IDs to ignore.

2023-10-02 23:41 UTC, another-rex commented on internal/output/fixtures/sarif-output.md
> +
> Does it change depending on what vulnerabilities are in my specific project?

Yep, so the vulnerability ID, link, the contents of the Source table and Fixed table will change depending on what vulnerability this help entry is for and what lockfiles are found in the scan.

2023-10-02 23:43 UTC, another-rex commented on internal/output/fixtures/sarif-output.md
> +
>  Is this a sample of what a sarif output would look like?

Yep, though only a partial sample. A SARIF file can contain multiple rules (in our case ), and each rule can have a "helpText". This is what the helpText contains

2023-10-03 02:15 UTC, another-rex commented on internal/output/fixtures/sarif-output.md
> +`path/to/lockfile-parent-dir/osv-scanner.toml`
Yep, updated this so the path is automatically filled.

2023-10-03 02:30 UTC, oliverchang approved these changes

2023-10-03 17:30 UTC, hayleycd commented on internal/output/fixtures/sarif-output.md
> +> issue. The fix is include starting from  `regex` 1.5.5.
This should be included, not include. 

Not sure if you can adjust this line or if you need to adjust a different file because this is a sample output.

2023-10-03 17:32 UTC, hayleycd commented on internal/output/fixtures/vuln-grouped.json
> +      "details": "\u003e This is a cross-post of [the official security advisory][advisory]. The official advisory contains a signed version with our PGP key, as well.\n\n[advisory]: https://groups.g
Maybe this is where you can fix the tense? Should be included, not include.

2023-10-03 17:33 UTC, hayleycd commented on internal/output/fixtures/vuln-grouped.json
> +      "details": "The Rust Security Response WG was notified that the `regex` crate did not\nproperly limit the complexity of the regular expressions (regex) it parses. An\nattacker could use this se
Wrong tense for include.

2023-10-03 17:53 UTC, hayleycd requested changes
Fix the verb tenses noted and it'll be ready to go.

2023-10-03 23:42 UTC, another-rex commented on internal/output/fixtures/sarif-output.md
> +> issue. The fix is include starting from  `regex` 1.5.5.
We can't adjust any of the lines beginning with `>` since those are just quotes from the actual advisory. Only the lines that don't start with `>` can be changed. See https://github.com/google/osv-scanner/pull/559/files#diff-d35339a2a0d00fb1bdef55bde8021cf88c25c1817a1d1f8afcfd734a1e80a784L29 for the template that is used to generate these files.

2023-10-04 03:44 UTC, oliverchang approved these changes

2023-10-04 22:40 UTC, merged