Downgrade go.mod
google/osv-scanner pull request #833
Opened 2024-02-29 05:05 UTC by another-rex

It was accidentally updated to 1.22.0 with renovatebot 2 weeks ago. We need a way to prevent this from happening.

2024-02-29 05:07 UTC, michaelkedar approved these changes

2024-03-05 23:14 UTC, michaelkedar requested changes

2024-03-06 00:47 UTC, another-rex commented on go.mod
> +go 1.21.5
done!

2024-03-06 00:48 UTC, michaelkedar approved these changes

2024-03-06 00:53 UTC, merged